// Decompiled with JetBrains decompiler
// Type: Intermech.Vault.Service.SQLCommands
// Assembly: Intermech.Vault.Service, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: 24B0DA67-997A-4E40-A745-DAEE647016D5
// Assembly location: D:\IPS\IPS.Installer.Full\InstServer\Server\Intermech.Vault.Service.exe

#nullable disable
namespace Intermech.Vault.Service;

internal static class SQLCommands
{
  internal static string SelectFileInfo = "SELECT * FROM files_registry WHERE F_FILE_ID=@blobid AND F_FOLDER_NAME='work'";
  internal static string SelectFileForObjectID = "SELECT * FROM files_registry WHERE F_OBJECT_ID=@objectID AND F_HISTORY_ID=@historyID";
  internal static string SelectVersionHistory = "SELECT F_OBJECT_ID, F_FILE_ID, F_HISTORY_ID, F_FILENAME, F_ZIPSIZE, \r\n                                                F_FILESIZE, datetime(F_CHANGE_DATE), F_USER_NAME, F_ARC_METHOD,\r\n                                                (F_FOLDER_NAME=='deleted') as 'F_DELETED',      \r\n                                                (F_FOLDER_NAME=='work') as 'F_WORK_COPY'\r\n                                                FROM [files_registry] f1 WHERE  F_OBJECT_ID=@objectID";
  internal static string SelectObjectHistory = "SELECT F_OBJECT_ID, F_FILE_ID, F_HISTORY_ID, F_FILENAME, F_ZIPSIZE, \r\n                                               F_FILESIZE, datetime(F_CHANGE_DATE), F_USER_NAME, F_ARC_METHOD,\r\n                                               (F_FOLDER_NAME=='deleted') as 'F_DELETED',\r\n                                               (F_FOLDER_NAME=='work') as 'F_WORK_COPY'\r\n                                               FROM [files_registry]  f1 WHERE F_ID=@id\r\n                                               ORDER BY F_FILE_ID, F_HISTORY_ID";
  internal static string SelectHistoryForBlobID = "SELECT F_OBJECT_ID, F_FILE_ID, F_HISTORY_ID, F_FILENAME, F_ZIPSIZE, \r\n                                               F_FILESIZE, datetime(F_CHANGE_DATE), F_USER_NAME, F_ARC_METHOD,\r\n                                               (F_FOLDER_NAME=='deleted') as 'F_DELETED',                                                    \r\n                                               (F_FOLDER_NAME=='work') as 'F_WORK_COPY'\r\n                                               FROM [files_registry]  f1 WHERE F_ID=@id AND F_FILE_ID=@blobID \r\n                                               ORDER BY F_FILE_ID, F_HISTORY_ID";
  internal static string SelectHistoryForFileName = "SELECT F_OBJECT_ID, F_FILE_ID, F_HISTORY_ID, F_FILENAME, F_ZIPSIZE, \r\n                                               F_FILESIZE, datetime(F_CHANGE_DATE), F_USER_NAME, F_ARC_METHOD,\r\n                                               (F_FOLDER_NAME=='deleted') as 'F_DELETED',\r\n                                               (F_FOLDER_NAME=='work') as 'F_WORK_COPY'\r\n                                               FROM [files_registry]  f1 WHERE F_ID=@id AND F_FILENAME=@fileName \r\n                                               ORDER BY F_FILE_ID, F_HISTORY_ID";
  internal static string SelectStorageInfo = "select count(*), sum(F_ZIPSIZE), sum(F_FILESIZE),\r\n                                            (select  count(*)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='history'),\r\n                                            (select  sum(F_ZIPSIZE)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='history'),\r\n                                            (select  sum(F_FILESIZE)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='history'),\r\n                                            (select count(*)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='deleted'),\r\n                                            (select sum(F_ZIPSIZE)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='deleted'),\r\n                                            (select sum(F_FILESIZE)\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='deleted')\r\n                                            from files_registry\r\n                                            where F_FOLDER_NAME='work'";
  internal static string CreatedWorkTable = "CREATE TABLE [work] (\r\n                    [F_KEY_ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n                    [F_VOLUME_NAME] varchar(100) NOT NULL,\r\n                    [F_MAX_SIZE] integer NOT NULL,\r\n                    [F_CURRENT] boolean DEFAULT 0\r\n                    )";
  internal static string insertDataIntoWorkTable = "INSERT INTO [work] (\r\n                    [F_VOLUME_NAME], [F_MAX_SIZE], [F_CURRENT]\r\n                    ) values (@folder, @maxsize, @current)";
  internal static string CreateHistoryTable = "CREATE TABLE [history] (\r\n                    [F_KEY_ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n                    [F_VOLUME_NAME] varchar(100) NOT NULL,\r\n                    [F_MAX_SIZE] integer NOT NULL,\r\n                    [F_CURRENT] boolean DEFAULT 0)";
  internal static string InsertDataIntoHistoryTable = "INSERT INTO [history] (\r\n                    [F_VOLUME_NAME], [F_MAX_SIZE], [F_CURRENT])\r\n                    values (@folder, @maxsize, @current)";
  internal static string CreateDeletedTable = "CREATE TABLE [deleted] (\r\n                    [F_KEY_ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n                    [F_VOLUME_NAME] varchar(100) NOT NULL,\r\n                    [F_MAX_SIZE] integer NOT NULL,\r\n                    [F_CURRENT] boolean DEFAULT 0)";
  internal static string InsertDataIntoDeletedTable = "INSERT INTO [deleted] (\r\n                    [F_VOLUME_NAME], [F_MAX_SIZE], [F_CURRENT]\r\n                    ) values (@folder, @maxsize, @current)";
  internal static string CreateFilesTable = "CREATE TABLE [files_registry] (\r\n                    [F_KEY_ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n                    [F_FOLDER_NAME] varchar(100) NOT NULL,\r\n                    [F_VOLUME_NAME] varchar(100) NOT NULL,\r\n                    [F_CHANGE_DATE] datetime(100) NOT NULL,\r\n                    [F_ID] integer NOT NULL,\r\n                    [F_FILE_ID] integer NOT NULL,\r\n                    [F_OBJECT_ID] integer NOT NULL,\r\n                    [F_HISTORY_ID] integer NOT NULL DEFAULT 0,\r\n                    [F_FILENAME] varchar(100) NOT NULL,\r\n                    [F_CREATE_DATE] datetime(100) NOT NULL,\r\n                    [F_USER_NAME] varchar(100) NOT NULL,\r\n                    [F_COMPUTER_NAME] varchar(100) NOT NULL,\r\n                    [F_ARC_METHOD] integer(10) NOT NULL,\r\n                    [F_ZIPSIZE] integer NOT NULL,\r\n                    [F_FILESIZE] integer NOT NULL,\r\n                    [F_NOTE] varchar(100))";
  internal static string CheckFileExists = "SELECT count(*) FROM files_registry\r\n                    WHERE F_FILE_ID=@blobid AND F_FOLDER_NAME='work'";
  internal static string SelectMaxHistoryID = "SELECT MAX(F_HISTORY_ID) FROM files_registry\r\n                        WHERE F_ID=@id";
  internal static string SelectCurrentVolumeInfo = "SELECT F_VOLUME_NAME, F_MAX_SIZE  FROM {0} WHERE F_CURRENT=1";
  internal static string CreateCurrentVolumeInfo = "INSERT INTO {0} (\r\n                    [F_VOLUME_NAME], [F_MAX_SIZE], [F_CURRENT]\r\n                    ) values (@folder, @maxsize, @current)";
  internal static string MoveFileFromWork = "UPDATE files_registry SET F_FOLDER_NAME=@folder_name, \r\n                                                F_VOLUME_NAME=@volume_name, F_USER_NAME=@user_name,\r\n                                                F_CHANGE_DATE=@change_date\r\n                                                WHERE F_FILE_ID=@blobid AND F_FOLDER_NAME='work'";
  internal static string SelectVolumeSize = "SELECT SUM(F_ZIPSIZE) FROM files_registry\r\n                                            WHERE F_VOLUME_NAME=@volume_name \r\n                                            AND F_FOLDER_NAME=@folder_name";
  internal static string SelectMaxSizeWorkVolume = "SELECT F_MAX_SIZE FROM work WHERE F_VOLUME_NAME=@volume_name";
  internal static string SelectVolumesSizes = "SELECT work.F_MAX_SIZE-SUM(F_ZIPSIZE), files_registry.F_VOLUME_NAME, work.F_CURRENT\r\n                                    FROM files_registry, work\r\n                                    WHERE F_FOLDER_NAME=@folder_name and work.F_VOLUME_NAME=files_registry.F_VOLUME_NAME \r\n                                    GROUP BY files_registry.F_VOLUME_NAME\r\n                                    HAVING files_registry.F_VOLUME_NAME IN (SELECT [F_VOLUME_NAME] FROM work)";
  internal static string InsertFileInfo = "INSERT INTO [files_registry] (\r\n                        [F_FOLDER_NAME], [F_VOLUME_NAME],[F_CHANGE_DATE],\r\n                        [F_ID],[F_FILE_ID],[F_OBJECT_ID],[F_HISTORY_ID],\r\n                        [F_FILENAME],[F_CREATE_DATE],[F_USER_NAME],[F_COMPUTER_NAME],\r\n                        [F_ARC_METHOD],[F_ZIPSIZE],[F_FILESIZE],[F_NOTE])\r\n                        values (@folder_name, @volume_name,@created_date,\r\n                        @id, @blobID, @objectID, @historyID,\r\n                        @file_name,@created_date, @user_name, @computer_name,\r\n                        @arc_method, @packed_size, @real_size, @note)";
  internal static string DeleteFileInfo = "DELETE FROM [files_registry]\r\n                                                  WHERE [F_FILE_ID]=@blobID";
  internal static string UpdateFileInfo = "UPDATE [files_registry] \r\n                        SET [F_FOLDER_NAME]=@folder_name, [F_VOLUME_NAME]= @volume_name,[F_CHANGE_DATE]=@created_date,\r\n                        [F_ID]= @id, [F_OBJECT_ID]=@objectID,\r\n                        [F_FILENAME]= @file_name,[F_CREATE_DATE]=@file_date,[F_USER_NAME]= @user_name,\r\n                        [F_COMPUTER_NAME]= @computer_name, [F_ARC_METHOD]= @arc_method,[F_ZIPSIZE]= @packed_size,\r\n                        [F_FILESIZE]= @real_size,[F_NOTE]=@note\r\n                        WHERE [F_FILE_ID]=@blobID";
  internal static string ChangeObjectLinkID = "UPDATE [files_registry] \r\n                        SET [F_OBJECT_ID]=@objectID                        \r\n                        WHERE [F_FILE_ID]=@blobID and [F_ID]=@id and [F_FOLDER_NAME]='work'";
  internal static string UpdateVolumeFileInfo = "UPDATE [files_registry] \r\n                        SET [F_FOLDER_NAME]=@folder_name, [F_VOLUME_NAME]= @volume_name,[F_CHANGE_DATE]=@created_date,\r\n                        [F_ID]= @id, [F_OBJECT_ID]=@objectID,[F_HISTORY_ID]= @historyID,\r\n                        [F_FILENAME]= @file_name,[F_CREATE_DATE]=@file_date,[F_USER_NAME]= @user_name,\r\n                        [F_COMPUTER_NAME]= @computer_name, [F_ARC_METHOD]= @arc_method,[F_ZIPSIZE]= @packed_size,\r\n                        [F_FILESIZE]= @real_size,[F_NOTE]=@note\r\n                        WHERE [F_FILE_ID]=@blobID";
  internal static string CloseCurrentVolume = "UPDATE {0} SET F_CURRENT=0 WHERE F_VOLUME_NAME=@volume_name";
  internal static string InsertNewVolume = "INSERT INTO {0} (F_VOLUME_NAME, F_MAX_SIZE, F_CURRENT) VALUES (@volume_name, @max_size, @current)";
  internal static string SelectTrashInfo = "SELECT F_ID, F_OBJECT_ID, F_FILE_ID, F_HISTORY_ID,\r\n                                                F_VOLUME_NAME, F_FOLDER_NAME\r\n                                                FROM [files_registry]\r\n                                                WHERE ((F_FOLDER_NAME='history') AND((julianday(@current_date)-julianday(F_CHANGE_DATE))>=@historyLife))\r\n                                                OR ((F_FOLDER_NAME='deleted') AND((julianday(@current_date)-julianday(F_CHANGE_DATE))>=@deletedLife))";
  internal static string DeleteTrashInfo = "DELETE FROM [files_registry]\r\n                                        WHERE ((F_FOLDER_NAME='history') AND ((julianday(@current_date)-julianday(F_CHANGE_DATE))>=@historyLife))\r\n                                                OR ((F_FOLDER_NAME='deleted') AND ((julianday(@current_date)-julianday(F_CHANGE_DATE))>=@deletedLife))";
  internal static string CheckWorkFilesExist = "SELECT count(*) FROM [files_registry] WHERE F_FOLDER_NAME='work'";
  internal static string SelectStorageFullSize = "SELECT total(F_ZIPSIZE) FROM [files_registry]";
  internal static string InsertTempFileInfo = "INSERT INTO {0} (\r\n                      [F_CHANGE_DATE],[F_ID],[F_FILE_ID],[F_OBJECT_ID],\r\n                      [F_HISTORY_ID], [F_FILENAME],[F_ARC_METHOD],[F_ZIPSIZE], \r\n                      [F_FILESIZE],[F_NOTE], [F_TEMP_NAME])\r\n                        values (@file_date, @id, @blobID, @objectID,\r\n                        @historyID, @file_name, @arc_method, @packed_size, \r\n                        @real_size, @note, @temp_name)";
  internal static string CreateTempFilesTable = "CREATE TABLE {0} (\r\n                    [F_KEY_ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,\r\n                    [F_TEMP_NAME] varchar(100) NOT NULL,                    \r\n                    [F_ID] integer NOT NULL,\r\n                    [F_FILE_ID] integer NOT NULL,\r\n                    [F_OBJECT_ID] integer NOT NULL,\r\n                    [F_HISTORY_ID] integer NOT NULL DEFAULT 0,\r\n                    [F_FILENAME] varchar(100) NOT NULL,\r\n                    [F_CHANGE_DATE] datetime(100) NOT NULL,                    \r\n                    [F_ARC_METHOD] integer(10) NOT NULL,\r\n                    [F_ZIPSIZE] integer NOT NULL,\r\n                    [F_FILESIZE] integer NOT NULL,\r\n                    [F_NOTE] varchar(100))";
  internal static string DropTempFilesTable = "DROP TABLE {0}";
  internal static string CheckTableExist = "SELECT name FROM sqlite_master WHERE name='{0}'";
  internal static string SelectTempFileInfo = "SELECT * FROM {0} WHERE F_FILE_ID=@blobid";
  internal static string SynchronousMode = "PRAGMA synchronous=NORMAL;\nPRAGMA journal_mode=WAL;";
}
