//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermech.XmlExchange.IpsXml.Converter.To1C.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intermech.XmlExchange.IpsXml.Converter.To1C.Resources.LogMessagesResources", typeof(LogMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект уже выгружался:.
        /// </summary>
        internal static string msgAlreadyExportedObject {
            get {
                return ResourceManager.GetString("msgAlreadyExportedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найденный МО не содержит дочерних элементов.
        /// </summary>
        internal static string msgEmptyPR {
            get {
                return ResourceManager.GetString("msgEmptyPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертациы составов головных изделий.
        /// </summary>
        internal static string msgExportAssemblies {
            get {
                return ResourceManager.GetString("msgExportAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формирование узла:.
        /// </summary>
        internal static string msgExportNode {
            get {
                return ResourceManager.GetString("msgExportNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка расчитанных значений параметров.
        /// </summary>
        internal static string msgExportPreparedParams {
            get {
                return ResourceManager.GetString("msgExportPreparedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По входимости не наден. Ищем с признаком по умолчанию среди МО без входимостей.
        /// </summary>
        internal static string msgFindDefalutPRWithoutVhod {
            get {
                return ResourceManager.GetString("msgFindDefalutPRWithoutVhod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск среди подходящий по входимости МО по умолчанию.
        /// </summary>
        internal static string msgFindDefaultPROnVhod {
            get {
                return ResourceManager.GetString("msgFindDefaultPROnVhod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию не найден. Берем первый в списке.
        /// </summary>
        internal static string msgFindFirstPROnVhod {
            get {
                return ResourceManager.GetString("msgFindFirstPROnVhod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию не найден. Берем первый в списке.
        /// </summary>
        internal static string msgFindFirstPRWithoutVhod {
            get {
                return ResourceManager.GetString("msgFindFirstPRWithoutVhod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество головных изделий:.
        /// </summary>
        internal static string msgHeadArtsCount {
            get {
                return ResourceManager.GetString("msgHeadArtsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка входных данных для конвертации.
        /// </summary>
        internal static string msgLoadInputData {
            get {
                return ResourceManager.GetString("msgLoadInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция завершена:.
        /// </summary>
        internal static string msgOperationComplete {
            get {
                return ResourceManager.GetString("msgOperationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден родительский объект у связи:.
        /// </summary>
        internal static string msgParentNotFoundForLink {
            get {
                return ResourceManager.GetString("msgParentNotFoundForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МО не найден.
        /// </summary>
        internal static string msgPRNotFound {
            get {
                return ResourceManager.GetString("msgPRNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для ИИ первый в списке МО:.
        /// </summary>
        internal static string msgProcessEcoRouteFound {
            get {
                return ResourceManager.GetString("msgProcessEcoRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для головной сборки первый в списке МО:.
        /// </summary>
        internal static string msgProcessHeadRouteFound {
            get {
                return ResourceManager.GetString("msgProcessHeadRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МО не найден для головной сборки.
        /// </summary>
        internal static string msgProcessHeadRouteNotFound {
            get {
                return ResourceManager.GetString("msgProcessHeadRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден подходящий МО:.
        /// </summary>
        internal static string msgProcessRouteFound {
            get {
                return ResourceManager.GetString("msgProcessRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подходящий МО не найден.
        /// </summary>
        internal static string msgProcessRouteNotFound {
            get {
                return ResourceManager.GetString("msgProcessRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация маршрутов обработки.
        /// </summary>
        internal static string msgProcessRoutesFiltering {
            get {
                return ResourceManager.GetString("msgProcessRoutesFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление пустых контейнеров:.
        /// </summary>
        internal static string msgRemovingEmptyItems {
            get {
                return ResourceManager.GetString("msgRemovingEmptyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден расцеховочный маршрут:.
        /// </summary>
        internal static string msgRouteFound {
            get {
                return ResourceManager.GetString("msgRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расцеховочный маршрут не найден.
        /// </summary>
        internal static string msgRouteNotFound {
            get {
                return ResourceManager.GetString("msgRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск подходящего расцеховочного маршрута.
        /// </summary>
        internal static string msgRoutesSearching {
            get {
                return ResourceManager.GetString("msgRoutesSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение результатов конвертации в файл:.
        /// </summary>
        internal static string msgSaveResultFile {
            get {
                return ResourceManager.GetString("msgSaveResultFile", resourceCulture);
            }
        }
    }
}
