// Decompiled with JetBrains decompiler
// Type: Intermech.ImpExp.TechCard.Pumpers.MetaData.ScenarioPump.ScenarioKind
// Assembly: Intermech.ImpExp.TechCard, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: 887E9725-1538-4175-97E8-C0643E4E85AA
// Assembly location: D:\IPS\Client\Intermech.ImpExp.TechCard.dll

#nullable disable
namespace Intermech.ImpExp.TechCard.Pumpers.MetaData.ScenarioPump;

internal enum ScenarioKind
{
  Unknown,
  Zagot,
  Oper,
  Rez,
  OperNorm,
  PerehConc,
  PerehNorm,
  Osn,
  Mat,
  Comm,
  AddMat,
  TipTp,
  Pmvm,
  OperMode,
  TpNorm,
  ZagPage,
  OperPage,
  OborPage,
  ToolPage,
  DetPage,
  DocPage,
  Surface,
  SurfacePage,
  Equipment,
  Reports,
  Dce,
  DcePage,
  SurfaceExt,
  Worker,
  WorkerPage,
  TpChange,
  KtpOper,
  KtpPereh,
  KtpObor,
  KtpTool,
  SpecTool,
  OsnArm,
  NormPerehConc,
  NormPerehRez,
  NormPerehNorm,
  Ktd,
  AutoParam,
  ConParPage,
  VsRep,
  VsRepPage,
  Route,
  RouteTemplate,
  RouteElement,
  ZagSourceSearch,
  ZagSourceImbase,
  RzIzw,
  KtdAlb,
  KtdPage,
  KtdAlbPage,
  MatSetCommon,
  KtdVedPage,
  MatConc,
  KtdSostavPage,
  ZakDocArtLink,
  GroupComm,
  TypeComm,
  Izw,
  RouteIzw,
  ZagIzw,
  MatIzw,
  MatGrIzw,
  IzwDocs,
  Arts,
  SingleGroupComm,
  SingleTypeComm,
  OperDiffTblPrototype,
  PerehDiffTblPrototype,
  TpDiffTblPrototype,
  NormDiffTblPrototype,
  AttachingGr,
  Attaching,
  NotLinkedOpers,
  LinkedTp2Route,
  SKtpPage,
  DceFromAnTp,
}
