[Kind]
Раздел СП = Article
Обозначение = Article
Исп. = Article
Код ОКП = Article
Наименование = Article
Литера = Article
Масса = Article
Покупной = Article
Материал = Article
Единица измерения = Article
Код версии = Document
Формат = Document
Примечание = Document
Масштаб = Document
Н.контр. = Document
Проверил = Document
Разработал = Document
Т.контр. = Document
Утвердил = Document
Тип документа1 = Document
Инв.N подл = Document
Перв.примен = Document
Справ.N = Document
Взам. инв.N = Document
Инв. N дубл. = Document
Инвентарный номер документа = Document
Номер версии = Article
Дата создания документа = Document
Ключ IMBASE = Article
Примечание для СП = Article


Нач.отд. = Document
Подп. и дата 1 = Document
Подп. и дата 2 = Document
MaterialID = Article
Литера2 = Article
Литера3 = Article
Подразделение = Document
Подразделение1 = Document
Материал замена1 = Article
MaterialID1 = Article
Материал замена2 = Article
MaterialID2 = Article
Изменение = Document
N извещения = Document
Тип документа в архиве = Document


[Common]
DocPrefix = DOC_
ArtPrefix = ART_

[Chars]
" " = "_"

[Names]
Инв.N подл = Инв№_подл
Перв.примен = Перв_примен
Справ.N = Справ№
Взам. инв.N = Взам_инв№
Инв. N дубл. = Инв№_дубл
Т.контр. = T_KONTR
Н.контр. = N_KONTR
;Тип документа = Тип_документа1
Дата создания документа = Дата_создания

Нач.отд. = Нач_отд
Подп. и дата 1 = Подп_и_дата_1
Подп. и дата 2 = Подп_и_дата_2


[Convert]
PROI_ = *
ART_Масса = MASS
DOC_Инвентарный_номер_документа = DocID


