[Settings]
ArchDocType=OFF
;Подавлять связи с базовым компонентом автоматически при возвращении в архив
;также настройка включает команды "Подавить" и "Восстановить", если не задана настройка SuppressReference_AUTO
SuppressReference_CMD=off
;Показать команды "Подавить" и "Восстановить"
SuppressReference_AUTO=Off

MaterialFromBase=OFF
LiteraFromList=OFF



[COMMON]
NOGOSTMULT=YES
BASEFORMAT=A3

[PropertyList]
Разработал
Проверил
Т.контр.
Н.контр.
Нач.отд.
Утвердил
Литера
Масса
Масштаб
Перв.примен
Справ.N
Инв.N подл
Подп. и дата 1
Взам. инв.N
Инв. N дубл.
Подп. и дата 2
Материал
Тип документа1
Литера2
Литера3
Подразделение
Материал замена 1
MaterialID1
Материал замена 2
MaterialID2
Изменение
N извещения
Тип документа в архиве
Раздел СП

[PropertyDefaults]
Разработал=Морозова
Проверил=Петров
Т.контр.=Иванов
Н.контр.=Сидоров
Нач.отд.=Зайцев
Утвердил=Конев

[Razrab]
Иванов
Морозова
Петров

[Prov]
Сидоров

[DocType]
Сборочный чертеж=СБ
Чертеж общего вида=ВО
Теоретический чертеж=ТЧ
Габаритный чертеж=ГЧ
Электромонтажный чертеж=МЭ
Монтажный чертеж=МЧ
Упаковочный чертеж=УЧ
Схема гидравлическая функциональная=Г2
Схема электрическая принципиальная=Э3

[Scale]
1:1
1:2
1:2,5
1:4
2:1
2,5:1
4:1


[TControl]
Петров

[UTV]
Чужба
Железняков



[NControl]
Зимницкий

[Massa]
0.5
1.2


[NOtd]
Булгак


[ArchSpIssue]
Комплексы
Комплекты
Стандартные изделия
Прочие изделия
Сборочные единицы
Детали
Документация

[Sortament]
Лист
Труба
Уголок
Квадрат
Швеллер
Двутавр
Тавр
Профиль
Круг
Шестигранник
Полоса
Лента
С-образный профиль


[Nonbreakspace]
ОСТ
СТП
DIN
ГОСТ

[Litera]
А



[NachOtd]
Н.сект.


;Настройка значений по умолчанию для массы
;первая колонка-значение массы (в кг)
;вторая колонка-точность в знаках. Точность с минусом указывает на округление до знака до запятой
;Через запятую указывается еденицы измерения, если не указаны-масса в колограммах
;масса от которой действует значение точности берется от предыдущей записи
;например точность 4 знака после запятой действует от массы 0.001 кг до 0.01 кг включительно
[MassaDefaults]
0.001= 1,г
0.01 = 4
0.1  = 3
1    = 2
10   = 2,кг
100  = 2,кг
1000 = 2,кг
>1000 =-2,кг

;Включает экспорт документов в момент возвращения в архив
;и определяет формат файлов для экспорта
[CadModelExtraFormats]
;ipt=jt
;iam=jt

;Включает экспорт документов в момент сохранения файла
;и определяет формат файлов для экспорта
[OnSaveExport]
;idw=pdf

;Параметры экспорта
[ExportParameters_IPT_JT]
FileStructure=0
XTBrep=1
OutputFileType=0
Version=95
IncludeSketches=1
Work Point Export=1
Work Axes Export=1
Work Plane Export=1

[ExportParameters_IAM_JT]
FileStructure=0
XTBrep=1
OutputFileType=0
Version=95
IncludeSketches=1
Work Point Export=1
Work Axes Export=1
Work Plane Export=1


[ExportParameters_IDW_PDF]
Sheets=-1
All_Color_AS_Black=0
Remove_Line_Weights=0
Vector_Resolution=400
Publish_Component_Props=1
Publish_Mass_Props=1


;Только для IPS. Включаек режим перекрытия команд в NX
;Перекрытые команды: Новый, Открыть, сохранить, Сохранить как, Довабить, Заменить компонент
[PDM_UG]
SubstFileCommands=0

;Список полей, которые будут читаться из модели и записываться обратно при редактировании карточки в чертеже.
[SYNCRONIZEPROPERTIES]
Обозначение
Наименование
Материал
MaterialID
Масса
Разработал
Проверил
Т.контр.
Н.контр.
Нач.отд.
Утвердил