// Decompiled with JetBrains decompiler
// Type: Intermech.ImpExp.Interface.ImportingCategory
// Assembly: Intermech.ImpExp.Interface, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: 37E5557D-7CCE-4F6F-9D9E-D0629D76BFC1
// Assembly location: D:\IPS\Client\Intermech.ImpExp.Interface.dll
// XML documentation location: D:\IPS\Client\Intermech.ImpExp.Interface.xml

using System.ComponentModel;

#nullable disable
namespace Intermech.ImpExp.Interface;

/// <summary>Категории объектов</summary>
[TypeConverter(typeof (EnumDescConverter))]
[Description("Категории объектов")]
[Category("Misc")]
public enum ImportingCategory
{
  None,
  [Description("Архивы")] Archives,
  [Description("Атрибуты изделий")] ArticleAttributes,
  [Description("Типы изделий")] ArticleTypes,
  [Description("Изделия")] Articles,
  [Description("Классификаторы")] Classificators,
  [Description("Картинки классификаторов")] ClassificatorsImages,
  [Description("Типы документов")] DocTypes,
  [Description("Настройки для типов документов")] Settings4DocTypes,
  [Description("Физические величины")] PhysicalValues,
  [Description("Единицы измерения")] Measures,
  [Description("Должности")] RankList,
  [Description("Выборки")] Selections,
  [Description("Картинки выборок")] SelectionsImages,
  [Description("Дерево выборок")] SelectionsTree,
  [Description("Группы тематических параметров")] ThematicParamsGroup,
  [Description("Тематические параметры")] ThematicParams,
  [Description("Группы пользователей")] UserGroups,
  [Description("Пользователи")] Users,
  [Description("Рабочие столы для пользователей")] Workspaces,
  [Description("Выборки Взятые на изменение объекты для пользователей")] CheckOutSelections,
  [Description("Выборки Моя корзина для пользователей")] TrashSelections,
  [Description("Связь между рабочим столом и выборкой Взятые на изменение объекты")] WorkspaceToCheckOut,
  [Description("Связь между рабочим столом и выборкой Моя корзина")] WorkspaceToMyTrash,
  [Description("Связь между группами пользователей и пользователями")] UsersToGroups,
  [Description("Guid импортированных объектов")] ObjectGUIDs,
  [Description("Создаваемые типы атрибутов")] AttributeTypesToCreate,
  [Description("Создаваемые типы объектов")] ObjectTypesToCreate,
  [Description("Создаваемые группы атрибутов")] AttributeGroupsToCreate,
  [Description("Связь между физическими величинами и единицами измерения")] PhysicalValuesToMeasures,
  [Description("TechCard Вид Работ")] TechWorkTypes,
  [Description("TechCard Заготовка")] TechZagot,
  [Description("TechCard идентификаторы родителей заготовок")] TechZagotParents,
  [Description("TechCard Расцеховочный маршрут")] TechRoute,
  [Description("TechCard Расцеховочный элемент")] TechRouteElem,
  [Description("TechCard Шаблон расцеховки базовый")] TechRouteTemplate,
  [Description("TechCard Цех")] TechCeh,
  [Description("TechCard Участок")] TechArea,
  [Description("TechCard Комментарий")] TechComment,
  [Description("TechCard Операция")] TechOperation,
  [Description("TechCard Эскиз OLE")] TechDraftOLE,
  [Description("TechCard Эскиз DWG")] TechDraftDWG,
  [Description("TechCard Маршрут обработки")] TechManufacturingRouting,
  [Description("TechCard Входимость в маршрут обработки")] TechManufacturingRoutingEntry,
  [Description("TechCard Входимость в маршрут обработки временная")] TechManufacturingRoutingEntryTemp,
  [Description("TechCard Связь расцеховки с заготовкой")] LinksTechRoute2ZagPump,
  [Description("TechCard Связь расцеховки с Техпроцессом")] LinksTechRoute2TpPump,
  [Description("TechCard Связь расцеховки с Техпроцессом через операции и элементы РМ")] LinksTechRoute2TpPumpOld,
  [Description("TechCard Связь с материалами")] LinksTechMaterialsPump,
  [Description("TechCard Техпроцесс")] TechProcessPump,
  [Description("TechCard Цехозаход")] TechCehZahodPump,
  [Description("TechCard Связь расцеховок с техпроцессами")] LinksTechRouteElem2OperPump,
  [Description("TechCard Оборудование")] TechOutfitPump,
  [Description("TechCard Оснастка")] TechToolsPump,
  [Description("TechCard Переход")] TechPerehPump,
  [Description("TechCard Персонал")] TechPersonalPump,
  [Description("TechCard Режимы")] TechRezPump,
  [Description("TechCard Изделия")] TechArticlesPump,
  [Description("TechCard Материалы")] TechMatPump,
  [Description("TechCard Группы материалов")] TechMatGrPump,
  [Description("TechCard Позиция")] TechOsnPos,
  [Description("TechCard Object:TechEntFixList")] Tech_C_EntFixList,
  [Description("TechCard Object:EntTypeList")] Tech_C_EntTypeList,
  [Description("TechCard Object:TechTypeRuleList")] Tech_C_TechTypeRuleList,
  [Description("TechCard Object:TechImTablesList")] Tech_C_TechImTablesList,
  [Description("TechCard Object:ArcArtList")] Tech_C_ArcArtList,
  [Description("TechCard Object:EntityRefList")] Tech_C_EntityRefList,
  [Description("TechCard Object:Code2AttributeGuid")] Tech_C_Code2AttributeGuid,
  [Description("TechCard Object:EntiyRefDirectoreList")] Tech_C_EnityRefDirectoreList,
  [Description("TechCard Object:TechTypeList")] Tech_C_TechTypeList,
  [Description("TechCard Object:TechTypeSettList")] Tech_C_TechTypeSettList,
  [Description("TechCard Object:ProductionList")] Tech_C_ProductionList,
  [Description("TechCard Object:ProductionSList")] Tech_C_ProductionSList,
  [Description("TechCard Object:MasterAtrlist")] Tech_C_MasterAtrlist,
  [Description("TechCard Object:EntitiesList")] Tech_C_EntitiesList,
  [Description("TechCard Измененеия ТП")] TechTPOverpatching,
  [Description("TechCard отложенные атрибуты")] TechSuspendedAtr,
  [Description("TechCard Доп. приемы")] TechAddMovement,
  [Description("TechCard инвентарные номера")] TechInvNomPump,
  [Description("TechCard Извещения об изменениях")] TechIzwPump,
  [Description("TechCard Условия автоподбора")] TechAutoSelCondPump,
  [Description("TechCard Сценарии")] TechScenarioPump,
  [Description("TechCard Параметры родительского объекта")] TechParentParametors,
  [Description("TechCard Виды заготовок")] TechVidZagPump,
  [Description("TechCard Виды изделий")] TechVidIzdPump,
  [Description("Информация по таблицам и каталогам Imbase")] ImbaseGroups,
  [Description("Привязка каталогов Imbase к уже существующим каталогам в новой базе")] ImbaseCatalogBinding,
  [Description("Тип синхронизации каталогов, с заменой состава или дополнением состава")] ImbaseCatalogBindingType,
  [Description("Настройки импорта каталогов")] ImbaseCatalogImportingFlags,
  [Description("Атрибуты для таблиц Imbase")] ImbaseTablesAttributes,
  [Description("Атрибуты таблиц Imbase")] ImbaseGroupsAttributes,
  [Description("Таблицы Imbase")] ImbaseTables,
  [Description("Каталоги Imbase")] ImbaseCatalogs,
  [Description("Созданные каталоги Imbase")] ImbaseCatalogsCreated,
  [Description("Блобы Imbase")] ImbaseBlobs,
  [Description("Папки Imbase")] ImbaseFolders,
  [Description("Глобальные идентификаторы папок Imbase")] ImbaseFoldersGuids,
  [Description("Ярлыки на таблицы Imbase")] ImbaseTableLinks,
  [Description("Ярлыки на таблицы Imbase в составе папок Imbase")] ImbaseTableLinksInFolders,
  [Description("Таблицы в каталогах Imbase")] ImbaseTablesInCatalogs,
  [Description("Таблица 'Свойства для объектов'")] ImbaseObjectProps,
  [Description("Записи таблицы 'Свойства для объектов'")] ImbaseObjectPropsItems,
  [Description("Параметры архива")] ArchiveParameters,
  [Description("Документы")] Documents,
  [Description("Файлы документов")] DocFiles,
  [Description("Материалы")] Materials,
  [Description("Материалы IMBASE")] ImbaseMaterials,
  [Description("Допустимые замены")] Substitutes,
  [Description("Допустимые замены в версиях")] VSubstitutes,
  [Description("Состав")] Composition,
  [Description("Связи документов")] DocRefs,
  [Description("Группы допустимых замен")] SubstitutesGroups,
  [Description("Группы допустимых замен версий")] VSubstitutesGroups,
  [Description("Состав версий")] VComposition,
  [Description("Связи документов с ИИ")] ECORefs,
  [Description("Атрибуты проектной связи")] CompositionAttributes,
  [Description("Процессы")] Processes,
  [Description("Пропущенные процессы")] ProcessesToSkip,
  [Description("Формы маршрутизатора")] Forms,
  [Description("Сценарии")] Scripts,
  [Description("Дерево архивов")] ArchivesTree,
  [Description("Документация")] Documentation,
  [Description("Поручения")] Resolutions,
  [Description("Категории опций")] ConfiguratorCategories,
  [Description("Опции")] ConfiguratorOptions,
  [Description("Значения опций")] ConfiguratorOptionValues,
  [Description("Настройки опций у изделий")] ConfiguratorOptionsToArticle,
  [Description("Настройки скрываемых значений опций у изделия")] ConfiguratorHideValOptionsToArticle,
  [Description("Несовместимость опций")] ConfiguratorRestrictRules,
  [Description("Условия применения")] ConfiguratorApplicabilitiesCriterions,
  [Description("Шаги ЖЦ для объектов архива")] LCSteps4Archives,
  [Description("Таймер импорта")] ImportingTimer,
  [Description("Настройки AVS")] AVSSettings,
  [Description("Группы шаблонов процессов")] SchemeCategories,
  [Description("Подписи")] Signs,
  [Description("Связи между библиотечным изображением и папкой библиотеки изображений")] ImbaseBlobToLibrary,
  [Description("Подпроцессы")] Subprocesses,
  [Description("Импортированные связи")] ImportedRelations,
  [Description("Импортированные записи из таблицы TC_PEREH_LINKS")] ImbaseTcPerehLinks,
  [Description("Импортированные записи из таблицы TC_COMMENTS_LINKS")] ImbaseTcCommectsLinks,
  [Description("Привязанные единицы измерения")] ImbaseBindedMeasures,
  [Description("Права доступа")] AccessRights,
  [Description("Данные фильтрации папок Imbase для Techcard")] ImbaseFolderFilters,
  [Description("Атрибуты для папок каталога оборудования")] OborudFolders,
  [Description("Типы данных для параметров оборудования")] OborudFieldTypes,
  [Description("Объекты экспертной системы")] TechExpTables,
  [Description("Структуры объектов экспертной системы")] TechExpObjStruct,
  [Description("Эскизы Техкард")] TechDrafts,
  [Description("Импортированная иерархия папок каталогов Imbase")] ImbaseFolderRelations,
  [Description("Счетчик идентификатора группового изделия")] GroupingID,
  [Description("Связи Оборудования и Операций")] TechOutfilt_InvNomLinks,
  [Description("Отложенные связи дерева материала")] TechMaterialPostLinks,
  [Description("Ключи Состава изделия")] TechArtCompositionKeys,
  [Description("Список связей Состава изделия")] TechArtComLinks,
  [Description("Список уникальных ключей оснастки")] TechOsnPosUnicalKeys,
  [Description("Список связей между Позицией и Инструментов")] TechPosInstrumLinks,
  [Description("TechCard Object: User's entities list")] Tech_C_EntitiesList_Org,
  [Description("Список связей между МО и ТП")] TechRoute2ArtLinks,
  [Description("Список списка внешних программ")] ExternalProgs,
  [Description("Внутренние ссылки Imbase для атрибутов папок")] ImbaseLinksFolder,
  [Description("Внутренние ссылки Imbase для атрибутов ссылок на таблицы")] ImbaseLinksTableLinks,
  [Description("Установленные внутренние ссылки Imbase")] ImbaseLinksCompleted,
  [Description("Связь ключей в кэше для папок Imbase (CATALOG_ID.FOLDER_KEY -> CATALOG_ID.FOLDER_LEVEL)")] ImbaseFolderKeyToLevel,
  [Description("TechCard Список уникальных расцеховочных элементов")] TechRouteElemUniqueCache,
  [Description("TechCard Список уникальных записей оборудования")] TechOutfitUniquePump,
  [Description("TechCard Список уникальных записей оснастки")] TechToolsUniquePump,
  [Description("TechCard Список уникальных записей извещений об изменениях")] TechIzwUniquePump,
  [Description("TechCard Список уникальных записей персонала")] TechPersonalUniquePump,
  [Description("Формы Search")] SearchForms,
  [Description("Изделия в заказах")] OrderArticles,
  [Description("Состав заказов")] OrderComposition,
  [Description("Головные изделия")] ArtFamilies,
  [Description("Номерные изделия")] ArtSeries,
  [Description("Документация на изделие")] DocLinks,
  [Description("TechCard Object:TechImFieldsList")] Tech_C_TechImFieldsList,
  [Description("TechCard идентификаторы родителей расцеховочных маршрутов")] TechRouteParents,
  [Description("Номерные изделия в IPS")] ObjectsWithSeries,
  [Description("TechCard Список типов атрибутов для технологических объектов")] TechAttributes2Exclude,
  [Description("TechCard Кэш конфигураций")] Tech_C_TechConfigs,
  [Description("TechCard Кэш уникальных записей материала")] TechMatUniquePump,
  [Description("Кэш связей между МО и ТП")] TechRoute2ArtUniqueLinks,
  [Description("Кэш изделий для решения проблем перекачки")] Articles2,
  [Description("TechCard Связь техпроцесса с заготовкой")] TechProc2ZagLinks,
  [Description("TechCard Корректировка оснастки")] TechToolsPumpFx,
  [Description("TechCard Согласование объектов ТП")] TechAgree,
  [Description("TechCard Расширенная информация о технологических объектах ")] TechObjectExtInfo,
  [Description("Листы рассылки ОТД")] OTDLists,
  [Description("Блобы таблиц Imbase")] ImbaseTableBlobs,
  [Description("TechCard Эскизы")] TechSketch,
  [Description("TechCard Эскизы DWG")] TechSketchDwg,
  [Description("Допустимые значения для атрибутов в контексте таблицы")] ImbasePVForTables,
  [Description("Кэш ссылок на таблицы: Код Imbase -> ObjectID")] ImbaseTableLinksKeyToObjectID,
  [Description("TechCard Кэш уникальных записей инвентарных номеров")] TechInvNomUniquePump,
  [Description("TechCard Кэш внутренних данных для материалов")] TechMatRawData,
  [Description("TechCard Связи с объектами сквозного ТП")] TechTPLinks,
  [Description("Кэш связей между РМ и заготовками")] LinksTechRoute2ZagUniqueLinks,
  [Description("Кэш связей между РМ и техпроцессами")] LinksTechRoute2TpUniqueLinks,
  [Description("Кэш связей ТП с изделиями")] Tech_C_Tp2ObjLinkList,
  [Description("TechCard Связь элементов расцеховок с шаблонами")] LinksTechRouteElemLinkPump,
  [Description("Кэш ссылок документов на документы (ИИ)")] DocLinksCache,
  [Description("TechCard таблицы инвентарных номеров")] TechInvNomTablePump,
  [Description("Классификаторы папок Imbase")] ImbaseFoldersClassificators,
  [Description("Идентификаторы перекачанных объектов")] IdGuids,
  [Description("Кэш id->тип объекта")] ObjectTypes,
  [Description("Соответствие статусов документов SEARCH уровням продвижения в IPS")] StatusesToLevels,
  [Description("Таблицы рецептур Imbase")] ImbaseMixTables,
  [Description("Позиции производственных заказов")] ProductionListsPositions,
  [Description("Объекты производственных заказов")] ProductionListsObjects,
  [Description("Атрибуты состава производственных заказов")] ProductionListsCompositionAttributes,
  [Description("Изделия - производственные заказы")] ProductionListsArticles,
  [Description("Изделия в составе производственных заказов")] ProductionListsComposition,
  [Description("TechCard Шаблон расцеховочного элемента")] TechRouteElemTemplate,
  [Description("TechCard Список уникальных шаблонов расцеховочных элементов")] TechRouteElemTemplateUniqueCache,
  [Description("Настройка документов Techcard")] TechcardDocumentSetup,
  [Description("Ссылки в копиях изделий - производственные заказы")] ProductionListsArticlesLinks,
  [Description("Идентификатор ПК ДСЕ в IPS")] ProductionСopyIDCache,
  [Description("TechCard Список уникальных описаний связей для записей извещений об изменениях")] TechIzwUniqueObjectLinkInfoPump,
  [Description("TechCard идентификаторы родителей групп материалов")] TechMatGroupParent,
  [Description("Кэш уникальных идентификаторов ПК ДСЕ")] ProductionСopyIDUniqueCache,
  [Description("Кэш производственных заказов для закачки")] EnabledProductionLists,
  [Description("Кэш связей производственных заказов с документами при докачке")] DocumentLinksToProductionLists,
  [Description("Кэш хэшей производственных копий")] ProductionCopiesHash,
  [Description("Кэш настроек производственных заказов для закачки")] SettingsProductionLists,
  [Description("Кэш хэшей документов для производственных ведомостей")] ProductionCopiesDocLinks,
  [Description("TechCard груповые заготовки")] TechZagotGroup,
  [Description("Список уникальных ключей груповых заготовок")] TechZagotGroupUniquePump,
  [Description("Кэш соответствия F_TCKEY из TP_VERSIONS Guid-у объекта Ips")] TcKeyToObjGuid,
  [Description("TechCard идентификаторы родителей групповых заготовок")] TechZagotGroupParents,
  [Description("Идентификатор изделия и ПК ДСЕ в IPS")] ArticlePCDSECache,
  [Description("TechCard инфоррмация о заменяемых материалах")] TechMaterialGroupReplaceableCache,
  [Description("TechCard инфоррмация о заменителях материалов")] TechMaterialGroupSubstituteCache,
  [Description("Общие параметры документов")] DocumentsCommonParameters,
  [Description("Общие параметры изделий")] ArticleCommonParameters,
  [Description("Кэш комплектов ведомостей")] VtdCache,
  [Description("Кэш актуальных версий технологических объектов")] BaseTechObjectsVersionsCache,
}
