// Decompiled with JetBrains decompiler
// Type: OxyPlot.Reporting.PlotModelExtensions
// Assembly: Intermech.Statistics, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: 407EEBC5-347E-45B1-B946-E45BC6430606
// Assembly location: D:\IPS\Client\Intermech.Statistics.dll

using OxyPlot.Annotations;
using OxyPlot.Axes;
using OxyPlot.Series;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;

#nullable disable
namespace OxyPlot.Reporting;

public static class PlotModelExtensions
{
  public static Report CreateReport(this PlotModel plotModel)
  {
    Report report = new Report()
    {
      Culture = CultureInfo.InvariantCulture
    };
    report.AddHeader(1, "P L O T   R E P O R T");
    report.AddHeader(2, "=== PlotModel ===");
    report.AddPropertyTable("PlotModel", (object) plotModel);
    report.AddHeader(2, "=== Axes ===");
    foreach (Axis ax in plotModel.Axes)
      report.AddPropertyTable(ax.GetType().Name, (object) ax);
    report.AddHeader(2, "=== Annotations ===");
    foreach (Annotation annotation in plotModel.Annotations)
      report.AddPropertyTable(annotation.GetType().Name, (object) annotation);
    report.AddHeader(2, "=== Series ===");
    foreach (OxyPlot.Series.Series series in plotModel.Series)
    {
      report.AddPropertyTable(series.GetType().Name, (object) series);
      if (series is DataPointSeries dataPointSeries)
      {
        List<ItemsTableField> fields = new List<ItemsTableField>()
        {
          new ItemsTableField("X", "X"),
          new ItemsTableField("Y", "Y")
        };
        report.AddItemsTable("Data", (IEnumerable) dataPointSeries.Points, (IList<ItemsTableField>) fields);
      }
    }
    AssemblyName assemblyName = new AssemblyName(Assembly.GetExecutingAssembly().FullName);
    report.AddParagraph($"Report generated by OxyPlot {assemblyName.Version.ToString(3)}");
    return report;
  }

  public static string CreateTextReport(this PlotModel plotModel)
  {
    using (MemoryStream memoryStream = new MemoryStream())
    {
      TextReportWriter w = new TextReportWriter((Stream) memoryStream);
      plotModel.CreateReport().Write((IReportWriter) w);
      w.Flush();
      memoryStream.Position = 0L;
      return new StreamReader((Stream) memoryStream).ReadToEnd();
    }
  }
}
