//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.Resources.LogMessagesResourc" +
                            "es", typeof(LogMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применение настроек логгирования....
        /// </summary>
        internal static string msg_apply_log_config {
            get {
                return ResourceManager.GetString("msg_apply_log_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивация результатов конвертации....
        /// </summary>
        internal static string msg_archive_results {
            get {
                return ResourceManager.GetString("msg_archive_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивация результатов конвертации завершена: {0}.
        /// </summary>
        internal static string msg_archive_results_complete {
            get {
                return ResourceManager.GetString("msg_archive_results_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение занесено в атрибут: id={0}; field={1}; value={2}.
        /// </summary>
        internal static string msg_attr_value_set {
            get {
                return ResourceManager.GetString("msg_attr_value_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация сущности с параметрами {0}....
        /// </summary>
        internal static string msg_base_dataentity_convertion {
            get {
                return ResourceManager.GetString("msg_base_dataentity_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация сущности с параметрами {0} завершена..
        /// </summary>
        internal static string msg_base_dataentity_convertion_complete {
            get {
                return ResourceManager.GetString("msg_base_dataentity_convertion_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация объекта {0}....
        /// </summary>
        internal static string msg_base_object_convertion {
            get {
                return ResourceManager.GetString("msg_base_object_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация объекта {0} завершена..
        /// </summary>
        internal static string msg_base_object_convertion_complete {
            get {
                return ResourceManager.GetString("msg_base_object_convertion_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация связи {0}....
        /// </summary>
        internal static string msg_base_relation_convertion {
            get {
                return ResourceManager.GetString("msg_base_relation_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая конвертация связи {0} завершена..
        /// </summary>
        internal static string msg_base_relation_convertion_complete {
            get {
                return ResourceManager.GetString("msg_base_relation_convertion_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кэширование конвертированного объекта....
        /// </summary>
        internal static string msg_cache_converted_object {
            get {
                return ResourceManager.GetString("msg_cache_converted_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кэширование конвертированного объекта завершено.
        /// </summary>
        internal static string msg_cache_converted_object_complete {
            get {
                return ResourceManager.GetString("msg_cache_converted_object_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет идентификатора....
        /// </summary>
        internal static string msg_calc_id {
            get {
                return ResourceManager.GetString("msg_calc_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор расчитан: {0}.
        /// </summary>
        internal static string msg_calc_id_complete {
            get {
                return ResourceManager.GetString("msg_calc_id_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет идентификатора части составной настройки.
        /// </summary>
        internal static string msg_calc_id_part_condition {
            get {
                return ResourceManager.GetString("msg_calc_id_part_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет идентификатора части составной настройки: {0}.
        /// </summary>
        internal static string msg_calc_id_part_condition_complete {
            get {
                return ResourceManager.GetString("msg_calc_id_part_condition_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет идентификатора групповой настройки.
        /// </summary>
        internal static string msg_calc_id_part_group_condition {
            get {
                return ResourceManager.GetString("msg_calc_id_part_group_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет идентификатора групповой настройки завершен: {0}.
        /// </summary>
        internal static string msg_calc_id_part_group_condition_complete {
            get {
                return ResourceManager.GetString("msg_calc_id_part_group_condition_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка условия идентификатора {0}.
        /// </summary>
        internal static string msg_check_id_config_condition {
            get {
                return ResourceManager.GetString("msg_check_id_config_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка условия составной части настройки: {0}....
        /// </summary>
        internal static string msg_check_id_part_condition {
            get {
                return ResourceManager.GetString("msg_check_id_part_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка условия группы составных частей: {0}....
        /// </summary>
        internal static string msg_check_id_part_group_condition {
            get {
                return ResourceManager.GetString("msg_check_id_part_group_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация дочернего объекта. {0}....
        /// </summary>
        internal static string msg_child_object_convertion {
            get {
                return ResourceManager.GetString("msg_child_object_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация дочернего объекта {0} завершена.
        /// </summary>
        internal static string msg_child_object_convertion_complete {
            get {
                return ResourceManager.GetString("msg_child_object_convertion_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла настроек: {0}....
        /// </summary>
        internal static string msg_config_file_loading {
            get {
                return ResourceManager.GetString("msg_config_file_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с настройками конвертации не найден: {0}.
        /// </summary>
        internal static string msg_config_file_not_found {
            get {
                return ResourceManager.GetString("msg_config_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден идентификатор: {0}.
        /// </summary>
        internal static string msg_config_id_found {
            get {
                return ResourceManager.GetString("msg_config_id_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор не найден..
        /// </summary>
        internal static string msg_config_id_not_found {
            get {
                return ResourceManager.GetString("msg_config_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка должна быть:  {0}.
        /// </summary>
        internal static string msg_config_must_be {
            get {
                return ResourceManager.GetString("msg_config_must_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка должна быть одним из типов:  {0}.
        /// </summary>
        internal static string msg_config_must_be_one_of {
            get {
                return ResourceManager.GetString("msg_config_must_be_one_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка не найдена..
        /// </summary>
        internal static string msg_config_not_found {
            get {
                return ResourceManager.GetString("msg_config_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметра: {0}....
        /// </summary>
        internal static string msg_convert_param {
            get {
                return ResourceManager.GetString("msg_convert_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметра: {0} завершена.
        /// </summary>
        internal static string msg_convert_param_complete {
            get {
                return ResourceManager.GetString("msg_convert_param_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация связи: {0}....
        /// </summary>
        internal static string msg_convert_relation {
            get {
                return ResourceManager.GetString("msg_convert_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация связи: {0} завершена.
        /// </summary>
        internal static string msg_convert_relation_complete {
            get {
                return ResourceManager.GetString("msg_convert_relation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект найден в  списке уже сконвертированных.
        /// </summary>
        internal static string msg_converted_data_found {
            get {
                return ResourceManager.GetString("msg_converted_data_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сущность не конвертировалась.
        /// </summary>
        internal static string msg_converted_data_not_found {
            get {
                return ResourceManager.GetString("msg_converted_data_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации объекта произошла критическая ошибка {0}. Аварийное завершение процедуры конвертации.
        /// </summary>
        internal static string msg_critical_error_object_convertion {
            get {
                return ResourceManager.GetString("msg_critical_error_object_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации параметра произошла критическая ошибка {0}. Аварийное завершение процедуры конвертации.
        /// </summary>
        internal static string msg_critical_error_param_convertion {
            get {
                return ResourceManager.GetString("msg_critical_error_param_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации связи произошла критическая ошибка {0}. Аварийное завершение процедуры конвертации.
        /// </summary>
        internal static string msg_critical_error_relation_convertion {
            get {
                return ResourceManager.GetString("msg_critical_error_relation_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные уже закэшированы:{0}. Добавление в кэш конвертированных данных отменено..
        /// </summary>
        internal static string msg_data_already_exists_in_cache {
            get {
                return ResourceManager.GetString("msg_data_already_exists_in_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект {0} закэширован с Id: {1}.
        /// </summary>
        internal static string msg_data_cached {
            get {
                return ResourceManager.GetString("msg_data_cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение варианта конвертации по умолчанию для типа: {0}.
        /// </summary>
        internal static string msg_default_convert_strategy {
            get {
                return ResourceManager.GetString("msg_default_convert_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение варианта конвертации по умолчанию для типа: {0} завершено.
        /// </summary>
        internal static string msg_default_convert_strategy_complete {
            get {
                return ResourceManager.GetString("msg_default_convert_strategy_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация вариантов конвертирования объектов по умолчанию....
        /// </summary>
        internal static string msg_default_strategies_initialization {
            get {
                return ResourceManager.GetString("msg_default_strategies_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация вариантов конвертирования объектов по умолчанию завершена.
        /// </summary>
        internal static string msg_default_strategies_initialization_complete {
            get {
                return ResourceManager.GetString("msg_default_strategies_initialization_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначен вариант конвертации по умолчанию {0} на тип: {1}.
        /// </summary>
        internal static string msg_default_strategy_initialized {
            get {
                return ResourceManager.GetString("msg_default_strategy_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл скопирован в дополнительную папку: %s.
        /// </summary>
        internal static string msg_dublicate_file_copied {
            get {
                return ResourceManager.GetString("msg_dublicate_file_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден дубликат файла %s в папке назначения.
        /// </summary>
        internal static string msg_dublicate_file_found {
            get {
                return ResourceManager.GetString("msg_dublicate_file_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое значение атрибута &quot;name&quot; в настройке id: {0}, проверяющей совпадение наименования и значения параметра.
        /// </summary>
        internal static string msg_empty_config_paramname {
            get {
                return ResourceManager.GetString("msg_empty_config_paramname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой идентификатор данных: {0}. Проверьте правила расчета идентификатора: {1}.
        /// </summary>
        internal static string msg_empty_data_id {
            get {
                return ResourceManager.GetString("msg_empty_data_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка идентификатора: {0}.
        /// </summary>
        internal static string msg_empty_id_config_found {
            get {
                return ResourceManager.GetString("msg_empty_id_config_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой идентификатор правила расчета идентификатора. Проверьте настройки {0}.
        /// </summary>
        internal static string msg_empty_unique_rule_id {
            get {
                return ResourceManager.GetString("msg_empty_unique_rule_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение занесено во внутреннее поле сущности: field={0}; value={1}.
        /// </summary>
        internal static string msg_ent_value_set {
            get {
                return ResourceManager.GetString("msg_ent_value_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сущность уже была конвертирована ранее {0}.
        /// </summary>
        internal static string msg_entity_already_converted {
            get {
                return ResourceManager.GetString("msg_entity_already_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация сущности: {0}.
        /// </summary>
        internal static string msg_entity_convertation {
            get {
                return ResourceManager.GetString("msg_entity_convertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация сущности завершена.
        /// </summary>
        internal static string msg_entity_convertation_complete {
            get {
                return ResourceManager.GetString("msg_entity_convertation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация сущности отключена в настройках: {0}.
        /// </summary>
        internal static string msg_entity_convertation_disabled {
            get {
                return ResourceManager.GetString("msg_entity_convertation_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров сущности {0}.
        /// </summary>
        internal static string msg_entity_params_convertation {
            get {
                return ResourceManager.GetString("msg_entity_params_convertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров сущности {0} завершена.
        /// </summary>
        internal static string msg_entity_params_convertation_complete {
            get {
                return ResourceManager.GetString("msg_entity_params_convertation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров сущности отключена в настройках: {0}.
        /// </summary>
        internal static string msg_entity_params_convertation_disabled {
            get {
                return ResourceManager.GetString("msg_entity_params_convertation_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип должен быть унаследован от:  {0}.
        /// </summary>
        internal static string msg_entity_type_must_be_inherited_from {
            get {
                return ResourceManager.GetString("msg_entity_type_must_be_inherited_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль уникальности сущности.
        /// </summary>
        internal static string msg_entity_unique_control {
            get {
                return ResourceManager.GetString("msg_entity_unique_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль уникальности сущности завершен.
        /// </summary>
        internal static string msg_entity_unique_control_complete {
            get {
                return ResourceManager.GetString("msg_entity_unique_control_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип узла совпадает: {0}.
        /// </summary>
        internal static string msg_equal_node_types {
            get {
                return ResourceManager.GetString("msg_equal_node_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение параметра совпадает: {0}={1}; тип:{2}.
        /// </summary>
        internal static string msg_equal_values {
            get {
                return ResourceManager.GetString("msg_equal_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки файла настроек: {0}.
        /// </summary>
        internal static string msg_error_config_file_loading {
            get {
                return ResourceManager.GetString("msg_error_config_file_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при создании варианта конвертации. Тип: {0}.
        /// </summary>
        internal static string msg_error_default_convert_strategy_create {
            get {
                return ResourceManager.GetString("msg_error_default_convert_strategy_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не возможно найти вариант конвертации по умолчанию. Отсутсвует объект конвертации или его тип.
        /// </summary>
        internal static string msg_error_default_convert_strategy_no_type_provided {
            get {
                return ResourceManager.GetString("msg_error_default_convert_strategy_no_type_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден дубликат варианта конвертации на тип: {0}. Варианты конвертации: {1} и {2}. Используется {1} вариант.
        /// </summary>
        internal static string msg_error_default_strategy_dublicate {
            get {
                return ResourceManager.GetString("msg_error_default_strategy_dublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка назначения варианта конвертации по умолчанию {0} на тип: {1}. Вариант не был создан..
        /// </summary>
        internal static string msg_error_default_strategy_initialization {
            get {
                return ResourceManager.GetString("msg_error_default_strategy_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое поле назначения значения параметра: {0}.
        /// </summary>
        internal static string msg_error_empty_value_dest_fieldname {
            get {
                return ResourceManager.GetString("msg_error_empty_value_dest_fieldname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список настроек значений пуст для настройки параметра: id={0}.
        /// </summary>
        internal static string msg_error_empty_values_config {
            get {
                return ResourceManager.GetString("msg_error_empty_values_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден: {0}.
        /// </summary>
        internal static string msg_error_file_not_found {
            get {
                return ResourceManager.GetString("msg_error_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный файл для конвертации не найден: {0}.
        /// </summary>
        internal static string msg_error_input_data_file_not_found {
            get {
                return ResourceManager.GetString("msg_error_input_data_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На тип {0} не назначен вариант конвертации по умолчанию..
        /// </summary>
        internal static string msg_error_no_default_convert_strategy_for_type {
            get {
                return ResourceManager.GetString("msg_error_no_default_convert_strategy_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено стратегии конвертирования по умолчанию для типа: {0}.
        /// </summary>
        internal static string msg_error_no_default_strategy_for_type {
            get {
                return ResourceManager.GetString("msg_error_no_default_strategy_for_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение параметра отсутствует в кэше. Настройки: param id:{0}; value id:{1}.
        /// </summary>
        internal static string msg_error_no_param_value_in_cache {
            get {
                return ResourceManager.GetString("msg_error_no_param_value_in_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении скрипта {0}{1}..
        /// </summary>
        internal static string msg_error_script_execution {
            get {
                return ResourceManager.GetString("msg_error_script_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип назначения значения параметра не поддерживается: {0}.
        /// </summary>
        internal static string msg_error_unsupported_value_destination {
            get {
                return ResourceManager.GetString("msg_error_unsupported_value_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка сущности в списке уже сконвертированных....
        /// </summary>
        internal static string msg_find_converted_data {
            get {
                return ResourceManager.GetString("msg_find_converted_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск параметра: &quot;{0}&quot;.
        /// </summary>
        internal static string msg_find_param {
            get {
                return ResourceManager.GetString("msg_find_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие идентификатора {0} сработало.
        /// </summary>
        internal static string msg_id_config_condition_applied {
            get {
                return ResourceManager.GetString("msg_id_config_condition_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие идентификатора {0} не сработало.
        /// </summary>
        internal static string msg_id_config_condition_not_applied {
            get {
                return ResourceManager.GetString("msg_id_config_condition_not_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдена настройка идентификатора Id:{0}.
        /// </summary>
        internal static string msg_id_config_found {
            get {
                return ResourceManager.GetString("msg_id_config_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена настройка идентификатора. Настройка Id:{0}.
        /// </summary>
        internal static string msg_id_config_not_found {
            get {
                return ResourceManager.GetString("msg_id_config_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групповое условие сработало.
        /// </summary>
        internal static string msg_id_part_group_condition_executed {
            get {
                return ResourceManager.GetString("msg_id_part_group_condition_executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групповое условие не сработало.
        /// </summary>
        internal static string msg_id_part_group_condition_not_executed {
            get {
                return ResourceManager.GetString("msg_id_part_group_condition_not_executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка исходного файла для конвертации: {0}....
        /// </summary>
        internal static string msg_load_input_data_file {
            get {
                return ResourceManager.GetString("msg_load_input_data_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл загружен успешно: {0}.
        /// </summary>
        internal static string msg_load_input_data_file_complete {
            get {
                return ResourceManager.GetString("msg_load_input_data_file_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки логгирования применены..
        /// </summary>
        internal static string msg_log_config_applied {
            get {
                return ResourceManager.GetString("msg_log_config_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации объекта произошла некритическая ошибка {0}.
        /// </summary>
        internal static string msg_minor_error_object_convertion {
            get {
                return ResourceManager.GetString("msg_minor_error_object_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации параметра произошла некритическая ошибка {0}..
        /// </summary>
        internal static string msg_minor_error_param_convertion {
            get {
                return ResourceManager.GetString("msg_minor_error_param_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время конвертации связи произошла некритическая ошибка {0}.
        /// </summary>
        internal static string msg_minor_error_relation_convertion {
            get {
                return ResourceManager.GetString("msg_minor_error_relation_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена настройка конвертации: {0}.
        /// </summary>
        internal static string msg_no_config_found {
            get {
                return ResourceManager.GetString("msg_no_config_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена настройка в файле конфигурации id: {0}.
        /// </summary>
        internal static string msg_no_config_with_id_found {
            get {
                return ResourceManager.GetString("msg_no_config_with_id_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден сконвертированный дочерний объект: {0} для связи: {1}.
        /// </summary>
        internal static string msg_no_converted_child_for_relation {
            get {
                return ResourceManager.GetString("msg_no_converted_child_for_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан конвертированная сущность-владелец параметра.
        /// </summary>
        internal static string msg_no_converted_params_owner_provided {
            get {
                return ResourceManager.GetString("msg_no_converted_params_owner_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден сконвертированный родительский объект: {0} для связи: {1}.
        /// </summary>
        internal static string msg_no_converted_parent_for_relation {
            get {
                return ResourceManager.GetString("msg_no_converted_parent_for_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан кэш конвертированных параметров.
        /// </summary>
        internal static string msg_no_params_cache_provided {
            get {
                return ResourceManager.GetString("msg_no_params_cache_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана сущность-владелец параметра.
        /// </summary>
        internal static string msg_no_params_owner_provided {
            get {
                return ResourceManager.GetString("msg_no_params_owner_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип узла не совпадает. Требуется: {0}. Текущий тип узла: {1}.
        /// </summary>
        internal static string msg_not_equal_node_types {
            get {
                return ResourceManager.GetString("msg_not_equal_node_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не совпадение значений параметров. Требуется: {0}={1}; тип:{2}.
        /// </summary>
        internal static string msg_not_equal_values {
            get {
                return ResourceManager.GetString("msg_not_equal_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют конвертированные файлы..
        /// </summary>
        internal static string msg_not_results_to_save {
            get {
                return ResourceManager.GetString("msg_not_results_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного варианта конвертации для объекта: {0}. Пропуск объекта.
        /// </summary>
        internal static string msg_not_strategies_found_for_obj {
            get {
                return ResourceManager.GetString("msg_not_strategies_found_for_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект сконвертирован: {0}.
        /// </summary>
        internal static string msg_obj_converted {
            get {
                return ResourceManager.GetString("msg_obj_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта должен быть одним из: {0}.
        /// </summary>
        internal static string msg_obj_type_must_be_one_of {
            get {
                return ResourceManager.GetString("msg_obj_type_must_be_one_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не поддерживаемый тип объекта: {0}..
        /// </summary>
        internal static string msg_obj_type_not_supported {
            get {
                return ResourceManager.GetString("msg_obj_type_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация дочерних связей объекта....
        /// </summary>
        internal static string msg_object_child_relations_convertation {
            get {
                return ResourceManager.GetString("msg_object_child_relations_convertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация дочерних связей объекта завершена..
        /// </summary>
        internal static string msg_object_child_relations_convertation_complete {
            get {
                return ResourceManager.GetString("msg_object_child_relations_convertation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекту назначен F_OBJECT_ID: {0}.
        /// </summary>
        internal static string msg_object_id_generated {
            get {
                return ResourceManager.GetString("msg_object_id_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не сконвертирован.
        /// </summary>
        internal static string msg_object_not_converted {
            get {
                return ResourceManager.GetString("msg_object_not_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация связей объекта {0}.
        /// </summary>
        internal static string msg_object_relations_convertation {
            get {
                return ResourceManager.GetString("msg_object_relations_convertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация связей объекта {0} завершена.
        /// </summary>
        internal static string msg_object_relations_convertation_complete {
            get {
                return ResourceManager.GetString("msg_object_relations_convertation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация дочерних связей объекта отключена в настройках: {0}.
        /// </summary>
        internal static string msg_object_relations_convertation_disabled {
            get {
                return ResourceManager.GetString("msg_object_relations_convertation_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип настройки параметра: {0} не поддерживается программой конвертации.
        /// </summary>
        internal static string msg_param_config_type_not_supported {
            get {
                return ResourceManager.GetString("msg_param_config_type_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр сконвертирован:{0}.
        /// </summary>
        internal static string msg_param_converted {
            get {
                return ResourceManager.GetString("msg_param_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр не сконвертирован.
        /// </summary>
        internal static string msg_param_not_converted {
            get {
                return ResourceManager.GetString("msg_param_not_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр не найден: &quot;{0}&quot;.
        /// </summary>
        internal static string msg_param_not_found {
            get {
                return ResourceManager.GetString("msg_param_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип родителя у настройки параметра: {0} id:{1} должен быть object. Текущий тип: {2}.
        /// </summary>
        internal static string msg_param_parent_type_must_be_object {
            get {
                return ResourceManager.GetString("msg_param_parent_type_must_be_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка настроек идентификаторов для расчета....
        /// </summary>
        internal static string msg_prepare_id_configs {
            get {
                return ResourceManager.GetString("msg_prepare_id_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка настроек идентификаторов для расчета завершена..
        /// </summary>
        internal static string msg_prepare_id_configs_complete {
            get {
                return ResourceManager.GetString("msg_prepare_id_configs_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь сконвертирована:{0}.
        /// </summary>
        internal static string msg_relation_converted {
            get {
                return ResourceManager.GetString("msg_relation_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связи назначен F_PRJLINK_ID: {0}.
        /// </summary>
        internal static string msg_relation_id_generated {
            get {
                return ResourceManager.GetString("msg_relation_id_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь не сконвертирована.
        /// </summary>
        internal static string msg_relation_not_converted {
            get {
                return ResourceManager.GetString("msg_relation_not_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров связи {0}.
        /// </summary>
        internal static string msg_relation_params_convertation {
            get {
                return ResourceManager.GetString("msg_relation_params_convertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров связи {0} завершена.
        /// </summary>
        internal static string msg_relation_params_convertation_complete {
            get {
                return ResourceManager.GetString("msg_relation_params_convertation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация параметров связи отключена в настройках: {0}.
        /// </summary>
        internal static string msg_relation_params_convertation_disabled {
            get {
                return ResourceManager.GetString("msg_relation_params_convertation_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление временных файлов....
        /// </summary>
        internal static string msg_remove_temp_files {
            get {
                return ResourceManager.GetString("msg_remove_temp_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головной объект сконвертирован {0}.
        /// </summary>
        internal static string msg_root_obj_converted {
            get {
                return ResourceManager.GetString("msg_root_obj_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация головного объекта. {0}....
        /// </summary>
        internal static string msg_root_object_convertion {
            get {
                return ResourceManager.GetString("msg_root_object_convertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация головного объекта: {0} завершена.
        /// </summary>
        internal static string msg_root_object_convertion_complete {
            get {
                return ResourceManager.GetString("msg_root_object_convertion_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение результатов на диск....
        /// </summary>
        internal static string msg_save_results_to_disk {
            get {
                return ResourceManager.GetString("msg_save_results_to_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение на диск завершено.
        /// </summary>
        internal static string msg_save_results_to_disk_complete {
            get {
                return ResourceManager.GetString("msg_save_results_to_disk_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении скрипта: {0}
        ///{1}..
        /// </summary>
        internal static string msg_script_error {
            get {
                return ResourceManager.GetString("msg_script_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение скрипта: {0}....
        /// </summary>
        internal static string msg_script_execution {
            get {
                return ResourceManager.GetString("msg_script_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение скрипта завершено {0}..
        /// </summary>
        internal static string msg_script_execution_complete {
            get {
                return ResourceManager.GetString("msg_script_execution_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат выполнения скрипта: {0}
        ///{1}..
        /// </summary>
        internal static string msg_script_result {
            get {
                return ResourceManager.GetString("msg_script_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск настройки для многозначного параметра: {0}.
        /// </summary>
        internal static string msg_search_array_param_config {
            get {
                return ResourceManager.GetString("msg_search_array_param_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск завершен. {0}. Id: {1}.
        /// </summary>
        internal static string msg_search_complete {
            get {
                return ResourceManager.GetString("msg_search_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск настройки....
        /// </summary>
        internal static string msg_search_config {
            get {
                return ResourceManager.GetString("msg_search_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск настройки конвертирования параметра по его наименованию: {0}.
        /// </summary>
        internal static string msg_search_param_config_by_param_name {
            get {
                return ResourceManager.GetString("msg_search_param_config_by_param_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск вариантов конвертации для: {0}....
        /// </summary>
        internal static string msg_search_strategy {
            get {
                return ResourceManager.GetString("msg_search_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск идентификатора настройки для: {0}.
        /// </summary>
        internal static string msg_searching_config_id {
            get {
                return ResourceManager.GetString("msg_searching_config_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор сессии: {0}.
        /// </summary>
        internal static string msg_session_id {
            get {
                return ResourceManager.GetString("msg_session_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт конвертации....
        /// </summary>
        internal static string msg_start_converting {
            get {
                return ResourceManager.GetString("msg_start_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация завершена..
        /// </summary>
        internal static string msg_start_converting_complete {
            get {
                return ResourceManager.GetString("msg_start_converting_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузка объекта варианта конвертирования объекта. Скрипт: {0}.
        /// </summary>
        internal static string msg_strategy_create {
            get {
                return ResourceManager.GetString("msg_strategy_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип должен быть: {0}.
        /// </summary>
        internal static string msg_target_must_be {
            get {
                return ResourceManager.GetString("msg_target_must_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка не прошла. Не поддерживаемый тип условия: {0}.
        /// </summary>
        internal static string msg_unsupported_condition_type {
            get {
                return ResourceManager.GetString("msg_unsupported_condition_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного головного в исходном файле: {0}.
        /// </summary>
        internal static string msg_warn_no_root_objects_found {
            get {
                return ResourceManager.GetString("msg_warn_no_root_objects_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая рабочая директория: {0}.
        /// </summary>
        internal static string msg_work_dir {
            get {
                return ResourceManager.GetString("msg_work_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указан подтип параметра в настройке Id:{0} Объект:{1}.
        /// </summary>
        internal static string msg_wrong_param_sub_type {
            get {
                return ResourceManager.GetString("msg_wrong_param_sub_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно выбран вариант конвертации объекта.{0}.
        /// </summary>
        internal static string msg_wrong_strategy_selected_for_obj {
            get {
                return ResourceManager.GetString("msg_wrong_strategy_selected_for_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно выбран вариант конвертации параметра.{0}.
        /// </summary>
        internal static string msg_wrong_strategy_selected_for_param {
            get {
                return ResourceManager.GetString("msg_wrong_strategy_selected_for_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно выбран вариант конвертации связи.{0}.
        /// </summary>
        internal static string msg_wrong_strategy_selected_for_relation {
            get {
                return ResourceManager.GetString("msg_wrong_strategy_selected_for_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно записать в защищенное поле: {0} Значение: {1}.  Настройка: id={0}.
        /// </summary>
        internal static string msgCantWriteToProtectedField {
            get {
                return ResourceManager.GetString("msgCantWriteToProtectedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис настроек конвертации.
        /// </summary>
        internal static string msgConfigService {
            get {
                return ResourceManager.GetString("msgConfigService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация завершена.
        /// </summary>
        internal static string msgConvertationComplete {
            get {
                return ResourceManager.GetString("msgConvertationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало конвертации.
        /// </summary>
        internal static string msgConvertationStart {
            get {
                return ResourceManager.GetString("msgConvertationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кэш конвертированных сущностей.
        /// </summary>
        internal static string msgConvertedCacheService {
            get {
                return ResourceManager.GetString("msgConvertedCacheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис вызова и выполнения стратегий конвертации.
        /// </summary>
        internal static string msgConvertStrategyService {
            get {
                return ResourceManager.GetString("msgConvertStrategyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис информации о текущей сессии конвертации.
        /// </summary>
        internal static string msgCurrentSessionInfoService {
            get {
                return ResourceManager.GetString("msgCurrentSessionInfoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое значение в расчетном параметре. Настройка: id={0}.
        /// </summary>
        internal static string msgEmptyValueInCalcParam {
            get {
                return ResourceManager.GetString("msgEmptyValueInCalcParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое значение в группе. Настройка: id={0}.
        /// </summary>
        internal static string msgEmptyValueInGroup {
            get {
                return ResourceManager.GetString("msgEmptyValueInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис конвертации значений параметров.
        /// </summary>
        internal static string msgEntityValueConvertService {
            get {
                return ResourceManager.GetString("msgEntityValueConvertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис по расчету и поиску идентификаторов сущностей и их настроек.
        /// </summary>
        internal static string msgIdConfigService {
            get {
                return ResourceManager.GetString("msgIdConfigService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис чтения входных данных.
        /// </summary>
        internal static string msgInputDataService {
            get {
                return ResourceManager.GetString("msgInputDataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертации.
        /// </summary>
        internal static string msgLoadConfigFile {
            get {
                return ResourceManager.GetString("msgLoadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис ведения логов.
        /// </summary>
        internal static string msgLogService {
            get {
                return ResourceManager.GetString("msgLogService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация объекта: .
        /// </summary>
        internal static string msgObjectConvertation {
            get {
                return ResourceManager.GetString("msgObjectConvertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип владельца парамера не поддерживается {0}.
        /// </summary>
        internal static string msgParamParentTypeNotSupported {
            get {
                return ResourceManager.GetString("msgParamParentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис сериализатор.
        /// </summary>
        internal static string msgSerializationService {
            get {
                return ResourceManager.GetString("msgSerializationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация сервиса: .
        /// </summary>
        internal static string msgServiceRegistration {
            get {
                return ResourceManager.GetString("msgServiceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис генерации уникальных идентификаторов.
        /// </summary>
        internal static string msgUniqueIdGenService {
            get {
                return ResourceManager.GetString("msgUniqueIdGenService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивация результатов конвертации.
        /// </summary>
        internal static string msgZippingResults {
            get {
                return ResourceManager.GetString("msgZippingResults", resourceCulture);
            }
        }
    }
}
