//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.Config.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.Config.Resources.LogMessages" +
                            "Resources", typeof(LogMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка сохранена.
        /// </summary>
        internal static string msg_config_serialized {
            get {
                return ResourceManager.GetString("msg_config_serialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сериализатор: {0} для типа: {1} инициализирован успешно..
        /// </summary>
        internal static string msg_config_serializer_initialized {
            get {
                return ResourceManager.GetString("msg_config_serializer_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация сериализаторов настроек....
        /// </summary>
        internal static string msg_config_serializers_initialization {
            get {
                return ResourceManager.GetString("msg_config_serializers_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация сериализаторов узлов настроек завершена..
        /// </summary>
        internal static string msg_config_serializers_initialization_complete {
            get {
                return ResourceManager.GetString("msg_config_serializers_initialization_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден дубликат настройки с Id: {0}. Настройка не будет использована..
        /// </summary>
        internal static string msg_dublicate_config_id {
            get {
                return ResourceManager.GetString("msg_dublicate_config_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка правил конвертирования: {0}.
        /// </summary>
        internal static string msg_empty_convert_rules_config {
            get {
                return ResourceManager.GetString("msg_empty_convert_rules_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка вариантов конвертаций: {0}.
        /// </summary>
        internal static string msg_empty_convert_strategies_config {
            get {
                return ResourceManager.GetString("msg_empty_convert_strategies_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка параметров {0}.
        /// </summary>
        internal static string msg_empty_param_configs {
            get {
                return ResourceManager.GetString("msg_empty_param_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка связей {0}.
        /// </summary>
        internal static string msg_empty_relation_configs {
            get {
                return ResourceManager.GetString("msg_empty_relation_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая настройка правил контроля уникальности: {0}.
        /// </summary>
        internal static string msg_empty_unique_rules_config {
            get {
                return ResourceManager.GetString("msg_empty_unique_rules_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сохранения настройки {0}.
        /// </summary>
        internal static string msg_error_config_serialization {
            get {
                return ResourceManager.GetString("msg_error_config_serialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка инициализации сериализатора: {0}..
        /// </summary>
        internal static string msg_error_config_serializer_initialization {
            get {
                return ResourceManager.GetString("msg_error_config_serializer_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой контекст в настройках службы конвертирования значений параметров. Узел: {0}.
        /// </summary>
        internal static string msg_error_empty_context_convert_value {
            get {
                return ResourceManager.GetString("msg_error_empty_context_convert_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое конвертированное значение в настройках службы конвертирования значений параметров. Узел: {0}.
        /// </summary>
        internal static string msg_error_empty_converted_value {
            get {
                return ResourceManager.GetString("msg_error_empty_converted_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки настроек вариантов конвертирования. Проверьте настройки узла: {0}.
        /// </summary>
        internal static string msg_error_loading_strategies {
            get {
                return ResourceManager.GetString("msg_error_loading_strategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки объекта настроек для узла: {0}. Пропуск настройки..
        /// </summary>
        internal static string msg_error_node_config_load {
            get {
                return ResourceManager.GetString("msg_error_node_config_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка инициализации загрузчика: {0}..
        /// </summary>
        internal static string msg_error_node_loader_initialization {
            get {
                return ResourceManager.GetString("msg_error_node_loader_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов метода загрузки: {0}.
        /// </summary>
        internal static string msg_invoke_load_method {
            get {
                return ResourceManager.GetString("msg_invoke_load_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов метода сериализации {0}.
        /// </summary>
        internal static string msg_invoke_serialize_method {
            get {
                return ResourceManager.GetString("msg_invoke_serialize_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настройки....
        /// </summary>
        internal static string msg_load_base_config_params {
            get {
                return ResourceManager.GetString("msg_load_base_config_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настройки: Id={0} Name={1} завершена..
        /// </summary>
        internal static string msg_load_base_config_params_complete {
            get {
                return ResourceManager.GetString("msg_load_base_config_params_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настроек, поддерживающего варианты конвертирования....
        /// </summary>
        internal static string msg_load_base_convertable_entity_config {
            get {
                return ResourceManager.GetString("msg_load_base_convertable_entity_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настроек, поддерживающего варианты конвертирования завершена.
        /// </summary>
        internal static string msg_load_base_convertable_entity_config_complete {
            get {
                return ResourceManager.GetString("msg_load_base_convertable_entity_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настроек, поддерживающего варианты конвертирования и настройки параметров.
        /// </summary>
        internal static string msg_load_base_convertable_entity_with_params_config {
            get {
                return ResourceManager.GetString("msg_load_base_convertable_entity_with_params_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка базовых параметров узла настроек, поддерживающего варианты конвертирования и настройки параметров.
        /// </summary>
        internal static string msg_load_base_convertable_entity_with_params_config_complete {
            get {
                return ResourceManager.GetString("msg_load_base_convertable_entity_with_params_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка узла {0}....
        /// </summary>
        internal static string msg_load_config {
            get {
                return ResourceManager.GetString("msg_load_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки идентификатора настройки....
        /// </summary>
        internal static string msg_load_config_id {
            get {
                return ResourceManager.GetString("msg_load_config_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки идентификатора настройки завершена..
        /// </summary>
        internal static string msg_load_config_id_complete {
            get {
                return ResourceManager.GetString("msg_load_config_id_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек идентификаторов настроек....
        /// </summary>
        internal static string msg_load_config_ids {
            get {
                return ResourceManager.GetString("msg_load_config_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек идентификаторов настроек завершена..
        /// </summary>
        internal static string msg_load_config_ids_complete {
            get {
                return ResourceManager.GetString("msg_load_config_ids_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек именованной константы....
        /// </summary>
        internal static string msg_load_const_value_config {
            get {
                return ResourceManager.GetString("msg_load_const_value_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек именованной константы завершена..
        /// </summary>
        internal static string msg_load_const_value_config_complete {
            get {
                return ResourceManager.GetString("msg_load_const_value_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка коллекции настроек именованных констант....
        /// </summary>
        internal static string msg_load_const_value_configs {
            get {
                return ResourceManager.GetString("msg_load_const_value_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка коллекции настроек именованных констант завершена..
        /// </summary>
        internal static string msg_load_const_value_configs_complete {
            get {
                return ResourceManager.GetString("msg_load_const_value_configs_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертированного значения параметра....
        /// </summary>
        internal static string msg_load_converted_value_config {
            get {
                return ResourceManager.GetString("msg_load_converted_value_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертированного значения параметра завершена.
        /// </summary>
        internal static string msg_load_converted_value_config_complete {
            get {
                return ResourceManager.GetString("msg_load_converted_value_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка составного идентификатора настроек....
        /// </summary>
        internal static string msg_load_id_config {
            get {
                return ResourceManager.GetString("msg_load_id_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка составного идентификатора настроек завершена..
        /// </summary>
        internal static string msg_load_id_config_complete {
            get {
                return ResourceManager.GetString("msg_load_id_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка группы настроек составных частей идентификатора настройки....
        /// </summary>
        internal static string msg_load_id_group_config {
            get {
                return ResourceManager.GetString("msg_load_id_group_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка группы настроек составных частей идентификатора настройки завершена..
        /// </summary>
        internal static string msg_load_id_group_config_complete {
            get {
                return ResourceManager.GetString("msg_load_id_group_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек логгирования....
        /// </summary>
        internal static string msg_load_log_config {
            get {
                return ResourceManager.GetString("msg_load_log_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек логгирования завершена..
        /// </summary>
        internal static string msg_load_log_config_complete {
            get {
                return ResourceManager.GetString("msg_load_log_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки конвертирования объекта....
        /// </summary>
        internal static string msg_load_obj_config {
            get {
                return ResourceManager.GetString("msg_load_obj_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки конвертирования объекта завершена..
        /// </summary>
        internal static string msg_load_obj_config_complete {
            get {
                return ResourceManager.GetString("msg_load_obj_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования объектов....
        /// </summary>
        internal static string msg_load_obj_configs {
            get {
                return ResourceManager.GetString("msg_load_obj_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования объектов завершена..
        /// </summary>
        internal static string msg_load_obj_configs_complete {
            get {
                return ResourceManager.GetString("msg_load_obj_configs_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек вариантов конвертирования объекта....
        /// </summary>
        internal static string msg_load_obj_strategies {
            get {
                return ResourceManager.GetString("msg_load_obj_strategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек вариантов конвертирования объекта завершена..
        /// </summary>
        internal static string msg_load_obj_strategies_complete {
            get {
                return ResourceManager.GetString("msg_load_obj_strategies_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка правил конвертации объекта....
        /// </summary>
        internal static string msg_load_object_convert_rules {
            get {
                return ResourceManager.GetString("msg_load_object_convert_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка правил конвертации объекта завершена.
        /// </summary>
        internal static string msg_load_object_convert_rules_complete {
            get {
                return ResourceManager.GetString("msg_load_object_convert_rules_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки варианта конвертирования объекта....
        /// </summary>
        internal static string msg_load_object_strategy {
            get {
                return ResourceManager.GetString("msg_load_object_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настройки варианта конвертирования объекта завершена..
        /// </summary>
        internal static string msg_load_object_strategy_complete {
            get {
                return ResourceManager.GetString("msg_load_object_strategy_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка правил контроля уникальности объекта....
        /// </summary>
        internal static string msg_load_object_unique_control_rule {
            get {
                return ResourceManager.GetString("msg_load_object_unique_control_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка правил контроля уникальности объекта завершена.
        /// </summary>
        internal static string msg_load_object_unique_control_rule_complete {
            get {
                return ResourceManager.GetString("msg_load_object_unique_control_rule_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертации значения параметра....
        /// </summary>
        internal static string msg_load_origin_value_config {
            get {
                return ResourceManager.GetString("msg_load_origin_value_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертации значения параметра завершена.
        /// </summary>
        internal static string msg_load_origin_value_config_complete {
            get {
                return ResourceManager.GetString("msg_load_origin_value_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек вывода....
        /// </summary>
        internal static string msg_load_output_config {
            get {
                return ResourceManager.GetString("msg_load_output_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек вывода завершена..
        /// </summary>
        internal static string msg_load_output_config_complete {
            get {
                return ResourceManager.GetString("msg_load_output_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертации параметра.
        /// </summary>
        internal static string msg_load_param_config {
            get {
                return ResourceManager.GetString("msg_load_param_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертации параметра завершена.
        /// </summary>
        internal static string msg_load_param_config_complete {
            get {
                return ResourceManager.GetString("msg_load_param_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования связи....
        /// </summary>
        internal static string msg_load_relation_config {
            get {
                return ResourceManager.GetString("msg_load_relation_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования связи завершена.
        /// </summary>
        internal static string msg_load_relation_config_complete {
            get {
                return ResourceManager.GetString("msg_load_relation_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования связей....
        /// </summary>
        internal static string msg_load_relation_configs {
            get {
                return ResourceManager.GetString("msg_load_relation_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования связей завершена.
        /// </summary>
        internal static string msg_load_relation_configs_complete {
            get {
                return ResourceManager.GetString("msg_load_relation_configs_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования значения параметра....
        /// </summary>
        internal static string msg_load_value_config {
            get {
                return ResourceManager.GetString("msg_load_value_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек конвертирования значения параметра завершена.
        /// </summary>
        internal static string msg_load_value_config_complete {
            get {
                return ResourceManager.GetString("msg_load_value_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек службы конвертации значений параметров....
        /// </summary>
        internal static string msg_load_value_converter {
            get {
                return ResourceManager.GetString("msg_load_value_converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек службы конвертации значений параметров завершена.
        /// </summary>
        internal static string msg_load_value_converter_complete {
            get {
                return ResourceManager.GetString("msg_load_value_converter_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек служб конвертации значений параметров....
        /// </summary>
        internal static string msg_load_value_converter_configs {
            get {
                return ResourceManager.GetString("msg_load_value_converter_configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек служб конвертации значений параметров завершена.
        /// </summary>
        internal static string msg_load_value_converter_configs_complete {
            get {
                return ResourceManager.GetString("msg_load_value_converter_configs_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка ссылки на службу конвертации значений параметров....
        /// </summary>
        internal static string msg_load_value_converter_reference_config {
            get {
                return ResourceManager.GetString("msg_load_value_converter_reference_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка ссылки на службу конвертации значений параметров завершена.
        /// </summary>
        internal static string msg_load_value_converter_reference_config_complete {
            get {
                return ResourceManager.GetString("msg_load_value_converter_reference_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден загрузчик: {0}.
        /// </summary>
        internal static string msg_loader_found {
            get {
                return ResourceManager.GetString("msg_loader_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден загрузчик для узла: {0}.
        /// </summary>
        internal static string msg_loader_not_found_for_node {
            get {
                return ResourceManager.GetString("msg_loader_not_found_for_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В контейнере настроек: id={0} name={1} не найдено дочерних настроек с типом: {2}.
        /// </summary>
        internal static string msg_no_childs_for_parent_found {
            get {
                return ResourceManager.GetString("msg_no_childs_for_parent_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В контейнере настроек: id={0} name={1} не найдено дочерних настроек с типами: {2} и {3}.
        /// </summary>
        internal static string msg_no_childs_for_parent_found_id_config_group {
            get {
                return ResourceManager.GetString("msg_no_childs_for_parent_found_id_config_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден метод загрузки в загрузчике: {0} для узла: {1}.
        /// </summary>
        internal static string msg_no_load_method_in_loader {
            get {
                return ResourceManager.GetString("msg_no_load_method_in_loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден метод сериализации в сериализаторе {0}.
        /// </summary>
        internal static string msg_no_serialize_method_in_serializer {
            get {
                return ResourceManager.GetString("msg_no_serialize_method_in_serializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют настройки вариантов конвертирования.
        /// </summary>
        internal static string msg_no_strategies_found {
            get {
                return ResourceManager.GetString("msg_no_strategies_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект настройки загружен..
        /// </summary>
        internal static string msg_node_config_loaded {
            get {
                return ResourceManager.GetString("msg_node_config_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузчик: {0} для типа: {1} инициализирован успешно..
        /// </summary>
        internal static string msg_node_loader_initialized {
            get {
                return ResourceManager.GetString("msg_node_loader_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация загрузчиков узлов настроек....
        /// </summary>
        internal static string msg_node_loaders_initialization {
            get {
                return ResourceManager.GetString("msg_node_loaders_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация загрузчиков узлов настроек завершена..
        /// </summary>
        internal static string msg_node_loaders_initialization_complete {
            get {
                return ResourceManager.GetString("msg_node_loaders_initialization_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парсинг файла настроек....
        /// </summary>
        internal static string msg_parse_config_file {
            get {
                return ResourceManager.GetString("msg_parse_config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парсинг файла завершен..
        /// </summary>
        internal static string msg_parse_config_file_complete {
            get {
                return ResourceManager.GetString("msg_parse_config_file_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение базовых параметров настройки {0}....
        /// </summary>
        internal static string msg_save_base_config_params {
            get {
                return ResourceManager.GetString("msg_save_base_config_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение базовых параметров настройки завершено..
        /// </summary>
        internal static string msg_save_base_config_params_complete {
            get {
                return ResourceManager.GetString("msg_save_base_config_params_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение базовых параметров настройки, поддерживающей варианты конвертирования....
        /// </summary>
        internal static string msg_save_base_convertable_entity_config {
            get {
                return ResourceManager.GetString("msg_save_base_convertable_entity_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение базовых параметров настройки, поддерживающей варианты конвертирования завершено.
        /// </summary>
        internal static string msg_save_base_convertable_entity_config_complete {
            get {
                return ResourceManager.GetString("msg_save_base_convertable_entity_config_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение настройки {0}....
        /// </summary>
        internal static string msg_serialize_config {
            get {
                return ResourceManager.GetString("msg_serialize_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден сериализатор {0}.
        /// </summary>
        internal static string msg_serializer_found {
            get {
                return ResourceManager.GetString("msg_serializer_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден сериализатор для настройки {0}.
        /// </summary>
        internal static string msg_serializer_not_found_for_config {
            get {
                return ResourceManager.GetString("msg_serializer_not_found_for_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки констант не найдены.
        /// </summary>
        internal static string msg_warn_const_value_configs_not_found {
            get {
                return ResourceManager.GetString("msg_warn_const_value_configs_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узел идентификатор настройки может содержать только один дочерний элемент: {0} или {1}
        ///Проверьте узел: node={2} Id={3} Name={4}
        ///В качестве источника данных будет выбран первый подходящий из списка дочерних.
        /// </summary>
        internal static string msg_warn_group_id_only_one_child_allowed {
            get {
                return ResourceManager.GetString("msg_warn_group_id_only_one_child_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки идентификаторов настроек не найдены.
        /// </summary>
        internal static string msg_warn_id_configs_not_found {
            get {
                return ResourceManager.GetString("msg_warn_id_configs_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки логгирования не найдены.
        ///Применены настройки логгирования по умолчанию.
        /// </summary>
        internal static string msg_warn_log_config_default {
            get {
                return ResourceManager.GetString("msg_warn_log_config_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует тег Id у узла настройки. node={0} Parent={1}.
        /// </summary>
        internal static string msg_warn_no_id_found_in_config {
            get {
                return ResourceManager.GetString("msg_warn_no_id_found_in_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки конвертирования объектов не найдены.
        /// </summary>
        internal static string msg_warn_object_configs_not_found {
            get {
                return ResourceManager.GetString("msg_warn_object_configs_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки вывода не найдены.
        /// </summary>
        internal static string msg_warn_output_config_not_found {
            get {
                return ResourceManager.GetString("msg_warn_output_config_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый тип настройки параметра. Узел настройки Id: {0}. Тип настройки: {1}.
        /// </summary>
        internal static string msg_warn_unsupported_param_config_type {
            get {
                return ResourceManager.GetString("msg_warn_unsupported_param_config_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки служб конвертации значений параметров не найдены.
        /// </summary>
        internal static string msg_warn_value_converters_configs_not_found {
            get {
                return ResourceManager.GetString("msg_warn_value_converters_configs_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла настроек..
        /// </summary>
        internal static string msg_wrong_config_file_format {
            get {
                return ResourceManager.GetString("msg_wrong_config_file_format", resourceCulture);
            }
        }
    }
}
