//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.ConfigEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intermech.XmlExchange.IpsXml.Converter.TechcardToIps.ConfigEditor.Resources.LogMe" +
                            "ssagesResources", typeof(LogMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор настроек.
        /// </summary>
        internal static string cptAppName {
            get {
                return ResourceManager.GetString("cptAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранные настройки?.
        /// </summary>
        internal static string msgAskToDeleteConfig {
            get {
                return ResourceManager.GetString("msgAskToDeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат:.
        /// </summary>
        internal static string msgCalcResultType {
            get {
                return ResourceManager.GetString("msgCalcResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие:.
        /// </summary>
        internal static string msgCondition {
            get {
                return ResourceManager.GetString("msgCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Константы.
        /// </summary>
        internal static string msgConstValuesConfig {
            get {
                return ResourceManager.GetString("msgConstValuesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила конвертации.
        /// </summary>
        internal static string msgConvertationRulesConfig {
            get {
                return ResourceManager.GetString("msgConvertationRulesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стратегии конвертации.
        /// </summary>
        internal static string msgConverterStrategyConfigs {
            get {
                return ResourceManager.GetString("msgConverterStrategyConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка с таким идентификатором уже присутствует в списке!.
        /// </summary>
        internal static string msgDublicateId {
            get {
                return ResourceManager.GetString("msgDublicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки идентификаторов настроек.
        /// </summary>
        internal static string msgIdConfigs {
            get {
                return ResourceManager.GetString("msgIdConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведение лога.
        /// </summary>
        internal static string msgLogConfig {
            get {
                return ResourceManager.GetString("msgLogConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертация объектов.
        /// </summary>
        internal static string msgObjectsConfig {
            get {
                return ResourceManager.GetString("msgObjectsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки вывода.
        /// </summary>
        internal static string msgOutputConfig {
            get {
                return ResourceManager.GetString("msgOutputConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки конвертации параметров.
        /// </summary>
        internal static string msgParamConfigs {
            get {
                return ResourceManager.GetString("msgParamConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки конвертации связей.
        /// </summary>
        internal static string msgRelationConfigs {
            get {
                return ResourceManager.GetString("msgRelationConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string msgSettings {
            get {
                return ResourceManager.GetString("msgSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип:.
        /// </summary>
        internal static string msgType {
            get {
                return ResourceManager.GetString("msgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила контроля уникальности.
        /// </summary>
        internal static string msgUniqueControlRuleConfig {
            get {
                return ResourceManager.GetString("msgUniqueControlRuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип.
        /// </summary>
        internal static string msgUnsupportedConfig {
            get {
                return ResourceManager.GetString("msgUnsupportedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки значений.
        /// </summary>
        internal static string msgValueConfigs {
            get {
                return ResourceManager.GetString("msgValueConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки конвертации значений.
        /// </summary>
        internal static string msgValueConvertersConfig {
            get {
                return ResourceManager.GetString("msgValueConvertersConfig", resourceCulture);
            }
        }
    }
}
